### ISSUE TITLE
Examples are incomplete

### ISSUE THREAD

**Issue by BrightSoul** [hashicorp/prebuild-webpack-plugin#20]
Hi, I tried to use this plugin but I just can't figure out how. Unfortunately, the documentation is not helping me.

The README states:
```
For instance, if you needed to transform files
```
That's my case but how should I do it? All these `any`'s are confusing.

```
function(compiler: any, compilation: any, changedFile: string[]): Promise<any> | optional
```
How should I write the function so that I can transform the content before it's fed into `babel-loader`?

Also, `compilationNameFilter` is not optional. What value should I use since I'm not using next.js?

<img width="496" alt="plugin-issue" src="https://user-images.githubusercontent.com/1888641/98528079-1a738700-227c-11eb-9d41-c114f7b58f14.png">

**Comment by jescalan** [comment]
There are no examples provided, so you are indeed correct that examples are incomplete. The plugin is provided as-is, you need to figure out how to use it yourself. If anyone is interested in contributing examples, I'd be happy to work with them on getting PRs accepted. But as it stands, it is not a requirement for all open source libraries to come with a comprehensive set of tutorials and examples.

I'll try to address your specific question here though, which seems to be "how to transform files". You can, inside of the build/watch functions, use `fs` and `path` to locate, read, and write to files. This read/writing will be completed before webpack starts its build. If you specify a matcher to the `files` argument, matched filenames will be passed in as an argument directly to the function, as `matchedFiles`. If this is still not clear enough, I would recommend holding off on using this library honestly. Going in to tinker with webpack's internals without a basic understanding of node's I/O is likely not going to end well.

As for the comment about typings such as `any` and `compilationNameFilter`, I'm not sure what to tell you here. This library is not written using typescript, so I don't know where the typings are coming from that are being used to give you these messages and warnings. Wherever it is, the types are of low quality and/or incorrect. For example, `compilationNameFilter` is optional. You can leave out `compilationNameFilter` and it will work fine. This is an issue that should be opened with whoever added these types, which are not part of this library.

I'm going to close this issue just because it does not point to an active problem, but please feel free to respond and continue discussion here if there's anything else I can help with!

**Comment by BrightSoul** [comment]
Hey @jescalan, thanks for the reply.

```
use fs and path to locate, read, and write to files
```
Oh, I see it now, I misinterpreted the goal of this package. It's used to `physically` modify files on disk.
Instead, I just needed to transform source code on-the-fly, before it was actually transformed by the babel loader. 
I ended up [writing a custom webpack loader](https://webpack.js.org/contribute/writing-a-loader/) like this one:
```
module.exports = function (source) {
  return transformSource(source);
};
```
And then using it like:
```
{
  enforce: 'pre',
  test: /\.js$/,
  include: /components/,
  exclude: /node_modules/,
  use: {
    loader: path.join(__dirname, './webpack.hot-loader.js')
  }
}
```

Thanks for your clarification.
